# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 22:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=16)),
                ('equipment_req', models.CharField(max_length=2048, null=True)),
                ('description', models.CharField(max_length=2048, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FacultyDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_workload', models.IntegerField()),
                ('changed_preferences', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=256, null=True)),
                ('capacity', models.IntegerField(default=0)),
                ('notes', models.CharField(max_length=1024, null=True)),
                ('equipment', models.CharField(max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_term', models.CharField(max_length=16, unique=True)),
                ('state', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('days', models.CharField(max_length=8)),
                ('section_capacity', models.IntegerField(default=0)),
                ('students_enrolled', models.IntegerField(default=0)),
                ('students_waitlisted', models.IntegerField(default=0)),
                ('conflict', models.CharField(max_length=1)),
                ('conflict_reason', models.CharField(max_length=8)),
                ('fault', models.CharField(max_length=1)),
                ('fault_reason', models.CharField(max_length=8)),
                ('course_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='css.Course')),
            ],
        ),
        migrations.CreateModel(
            name='SectionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('user_type', models.CharField(max_length=16)),
                ('email', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=128)),
                ('salt', models.CharField(max_length=128)),
                ('first_name', models.CharField(max_length=16)),
                ('last_name', models.CharField(max_length=16)),
            ],
        ),
        migrations.AddField(
            model_name='section',
            name='faculty',
            field=models.OneToOneField(default=django.db.models.deletion.SET_NULL, null=True, on_delete=django.db.models.deletion.SET_NULL, to='css.User'),
        ),
        migrations.AddField(
            model_name='section',
            name='room',
            field=models.OneToOneField(default=django.db.models.deletion.SET_NULL, null=True, on_delete=django.db.models.deletion.SET_NULL, to='css.Room'),
        ),
        migrations.AddField(
            model_name='section',
            name='schedule_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='css.Schedule'),
        ),
        migrations.AddField(
            model_name='facultydetails',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='css.User'),
        ),
    ]
