# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 18:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('css', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyWorkInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_units', models.IntegerField(default=0)),
                ('work_hours', models.IntegerField(default=0)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='css.Course')),
                ('section_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='css.SectionType')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='facultyworkinfo',
            unique_together=set([('course_id', 'section_type')]),
        ),
    ]
