# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 09:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('css', '0003_auto_20170208_0842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='cuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='cuser',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='cuser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='cuser',
            name='password',
        ),
        migrations.AddField(
            model_name='cuser',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cuser',
            name='user_type',
            field=models.CharField(choices=[(b's', b'scheduler'), (b'f', b'faculty')], default=b'f', max_length=1),
        ),
        migrations.AlterField(
            model_name='facultydetails',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='css.CUser'),
        ),
        migrations.AlterField(
            model_name='section',
            name='faculty',
            field=models.ForeignKey(default=django.db.models.deletion.SET_NULL, null=True, on_delete=django.db.models.deletion.SET_NULL, to='css.CUser'),
        ),
    ]
