# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 09:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('css', '0004_auto_20170208_0909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='schedule_id',
            new_name='schedule',
        ),
        migrations.RenameField(
            model_name='workinfo',
            old_name='course_id',
            new_name='course',
        ),
        migrations.AlterUniqueTogether(
            name='workinfo',
            unique_together=set([('course', 'section_type')]),
        ),
    ]
