# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('css', '0005_auto_20170208_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuser',
            name='user_type',
            field=models.CharField(max_length=16),
        ),
    ]
